<Project>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <Version>3.0.0</Version>

        <Authors>小方</Authors>
        <Product>Fast.Admin</Product>
        <Description>Fast.Admin 企业管理系统服务端，基于 Fast.NET 提供组织权限、系统配置、运行监控和任务调度能力。</Description>
        <Copyright>版权所有 © 2018-Now 小方</Copyright>

        <GenerateDocumentationFile>True</GenerateDocumentationFile>

        <SatelliteResourceLanguages>en-US;zh-CN</SatelliteResourceLanguages>
        <GenerateResxSourceIncludeDefaultValues>True</GenerateResxSourceIncludeDefaultValues>
    </PropertyGroup>

</Project>
